#!/bin/bash
# ============================================================================
# Script Debian ONLY : Configuration réseau (IP statique) + DNS + SSH hardening
# - Configure /etc/network/interfaces (ifupdown)
# - Met à jour /etc/resolv.conf (avec gestion de resolvconf/systemd-resolved)
# - Recrée /etc/ssh/sshd_config depuis zéro (avec backup horodaté)
# - Ajoute une clé SSH dans le compte appelant (SUDO_USER)
# ============================================================================
set -euo pipefail

# =========================
# Variables à personnaliser
# =========================
STATIC_IP="10.0.0.202/24"
GATEWAY="10.0.0.254"
DNS_LIST=("10.0.0.254" "1.1.1.1" "1.0.0.1")
SEARCH_DOMAINS=(test.auvergneinfo.lan)  # ex: ("corp.local" "lab.local") ou laisse vide
SSH_PORT="22"             				# Mets 2222 si tu changes vraiment
CLE_SSH_P="ssh-ed25519 AAAAC3NzaC1lZD steph@POC-PC"

# =========================
# Sudo / root
# =========================
check_sudo() {
  if [ "${EUID}" -ne 0 ]; then
    echo "Ce script nécessite des privilèges administrateur."
    echo "Relancement avec sudo..."
    exec sudo -E "$0" "$@"
  fi
}
check_sudo "$@"

# =========================
# Utilitaires
# =========================
die() { echo "ERREUR: $*" >&2; exit 1; }

detect_interface() {
  local iface
  iface="$(ip -o -4 route show to default 2>/dev/null | awk '{print $5}' | head -n1)"
  [ -n "$iface" ] || die "Impossible de détecter l'interface par défaut."
  echo "$iface"
}

prefix_to_netmask() {
  local p="$1"
  [ "$p" -ge 0 ] 2>/dev/null && [ "$p" -le 32 ] || die "Prefix invalide: $p"
  local full=$((p/8))
  local rem=$((p%8))
  local i mask=()
  for i in 0 1 2 3; do
    if [ "$i" -lt "$full" ]; then
      mask+=("255")
    elif [ "$i" -eq "$full" ]; then
      local val=$(( (rem==0) ? 0 : (256 - (1 << (8-rem))) ))
      mask+=("$val")
    else
      mask+=("0")
    fi
  done
  echo "${mask[0]}.${mask[1]}.${mask[2]}.${mask[3]}"
}

# =========================
# Réseau (Debian ifupdown)
# =========================
configure_network_debian() {
  echo "=== Configuration réseau Debian (ifupdown) ==="
  local iface ip_addr prefix netmask dns_debian
  iface="$(detect_interface)"
  echo "Interface détectée: $iface"
  ip_addr="${STATIC_IP%/*}"
  prefix="${STATIC_IP#*/}"
  netmask="$(prefix_to_netmask "$prefix")"
  dns_debian="$(printf '%s ' "${DNS_LIST[@]}")"
  [ -f /etc/network/interfaces ] || die "/etc/network/interfaces introuvable (ifupdown requis)."
  local backup="/etc/network/interfaces.backup.$(date +%F-%H%M%S)"
  cp /etc/network/interfaces "$backup"
  echo "Backup créé: $backup"
  cat > /etc/network/interfaces <<EOF
# ============================================================================
# /etc/network/interfaces - généré automatiquement le $(date)
# Backup: $backup
# ============================================================================
auto lo
iface lo inet loopback

allow-hotplug $iface
iface $iface inet static
  address $ip_addr
  netmask $netmask
  gateway $GATEWAY
  dns-nameservers $dns_debian
EOF
  echo "Redémarrage réseau..."
  if systemctl list-unit-files | grep -q '^networking\.service'; then
    systemctl restart networking.service || die "Échec restart networking.service"
  else
    (ifdown "$iface" 2>/dev/null || true)
    ifup "$iface" || die "Échec ifup $iface"
  fi
  echo "Réseau configuré: $ip_addr/$prefix via $GATEWAY"
}

# =========================
# DNS (/etc/resolv.conf)
# =========================
configure_resolv_conf() {
  echo "=== Configuration DNS (/etc/resolv.conf) ==="

  local RESOLV="/etc/resolv.conf"
  local backup="/etc/resolv.conf.backup.$(date +%F-%H%M%S)"
  [ -e "$RESOLV" ] && cp -a "$RESOLV" "$backup" && echo "Backup créé: $backup"
  RESOLV_BACKUP="$backup"

  # Construit le contenu cible
  local tmp
  tmp="$(mktemp)"
  {
    echo "# Generated by Debian-only network script on $(date)"
    if [ "${#SEARCH_DOMAINS[@]}" -gt 0 ]; then
      echo "search ${SEARCH_DOMAINS[*]}"
    fi
    for dns in "${DNS_LIST[@]}"; do
      echo "nameserver $dns"
    done
  } > "$tmp"

  # Cas 1: resolvconf (paquet resolvconf)
  if command -v resolvconf >/dev/null 2>&1; then
    echo "resolvconf détecté: mise à jour via /etc/resolvconf/resolv.conf.d/head"
    mkdir -p /etc/resolvconf/resolv.conf.d
    cp "$tmp" /etc/resolvconf/resolv.conf.d/head
    resolvconf -u || die "Échec resolvconf -u"
    rm -f "$tmp"
    return 0
  fi

  # Cas 2: systemd-resolved gère resolv.conf (souvent symlink)
  if systemctl is-active --quiet systemd-resolved 2>/dev/null; then
    # Si /etc/resolv.conf est un lien vers systemd, on évite d'écraser directement
    if [ -L "$RESOLV" ]; then
      echo "systemd-resolved actif et /etc/resolv.conf est un symlink."
      echo "Configuration via /etc/systemd/resolved.conf + restart systemd-resolved."
      local rbackup="/etc/systemd/resolved.conf.backup.$(date +%F-%H%M%S)"
      [ -f /etc/systemd/resolved.conf ] && cp /etc/systemd/resolved.conf "$rbackup" && echo "Backup: $rbackup"
      # Écrit un resolved.conf minimal (en gardant le reste commenté)
      # Note: systemd-resolved gère DNS= et Domains=
      local domains=""
      if [ "${#SEARCH_DOMAINS[@]}" -gt 0 ]; then
        domains="${SEARCH_DOMAINS[*]}"
      fi
      cat > /etc/systemd/resolved.conf <<EOF
[Resolve]
DNS=${DNS_LIST[*]}
Domains=${domains}
EOF
      systemctl restart systemd-resolved || die "Échec restart systemd-resolved"
      rm -f "$tmp"
      return 0
    fi
  fi
  # Cas 3: écriture directe (ifupdown classique)
  echo "Écriture directe de /etc/resolv.conf"
  cp "$tmp" "$RESOLV"
  chmod 644 "$RESOLV"
  rm -f "$tmp"
}

test_dns() {
  echo "=== Test DNS ==="
  echo "- Contenu resolv.conf :"
  sed -n '1,120p' /etc/resolv.conf || true
  echo "- Vérification présence des DNS attendus :"
  local missing=0
  for dns in "${DNS_LIST[@]}"; do
    if grep -qE "^[[:space:]]*nameserver[[:space:]]+$dns([[:space:]]+|$)" /etc/resolv.conf; then
      echo "  OK: $dns"
    else
      echo "  KO: $dns absent"
      missing=1
    fi
  done
  # Test résolution réelle (glibc / nss)
  if getent hosts google.com >/dev/null 2>&1; then
    echo "- Résolution DNS (getent) : OK"
    return $missing
  else
    echo "- Résolution DNS (getent) : ECHEC"
    return 1
  fi
}

rollback_resolv_conf_if_needed() {
  # À appeler juste après configure_resolv_conf
  # Repose sur la variable 'backup' créée dans configure_resolv_conf :
  #   backup="/etc/resolv.conf.backup.$(date ...)"
  #
  # Pour éviter les soucis de scope, on mémorise aussi le backup dans une variable globale.
  # -> Dans configure_resolv_conf, ajoute: RESOLV_BACKUP="$backup"
  echo "=== Validation + rollback resolv.conf si nécessaire ==="
  if test_dns; then
    echo "DNS validé, pas de rollback."
    return 0
  fi
  echo "ATTENTION: DNS invalide, rollback en cours..."
  if [ -n "${RESOLV_BACKUP:-}" ] && [ -e "$RESOLV_BACKUP" ]; then
    cp -a "$RESOLV_BACKUP" /etc/resolv.conf
    chmod 644 /etc/resolv.conf || true
    echo "Rollback effectué depuis: $RESOLV_BACKUP"
  else
    echo "Aucun backup resolv.conf disponible, rollback impossible."
    return 1
  fi
  echo "Re-test après rollback..."
  test_dns || { echo "ERREUR: DNS toujours invalide après rollback."; return 1; }
  echo "DNS OK après rollback."
}

# =========================
# SSH (recréation complète)
# =========================
configure_ssh_security() {
  echo "=== Sécurisation SSH (recréation complète de sshd_config) ==="
  local SSH_CONFIG="/etc/ssh/sshd_config"
  local BACKUP_FILE="/etc/ssh/sshd_config.backup.$(date +%F-%H%M%S)"
  local SFTP_PATH=""
  if [ -x /usr/libexec/openssh/sftp-server ]; then
    SFTP_PATH="/usr/libexec/openssh/sftp-server"
  elif [ -x /usr/lib/openssh/sftp-server ]; then
    SFTP_PATH="/usr/lib/openssh/sftp-server"
  else
    SFTP_PATH="internal-sftp"
  fi
  [ -f "$SSH_CONFIG" ] && cp "$SSH_CONFIG" "$BACKUP_FILE" && echo "Backup créé : $BACKUP_FILE"
  cat > "$SSH_CONFIG" <<EOF
# ============================================================================
# SSHD Configuration - Hardened (Debian)
# Généré automatiquement le $(date)
# ============================================================================

Port $SSH_PORT
Protocol 2

PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
PermitEmptyPasswords no

MaxAuthTries 3
LoginGraceTime 30

X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding no
PermitTunnel no

AuthorizedKeysFile .ssh/authorized_keys

SyslogFacility AUTH
LogLevel VERBOSE

UsePAM yes

Subsystem sftp $SFTP_PATH
EOF
  chmod 600 "$SSH_CONFIG"
  # Ajout clé SSH dans le compte appelant (SUDO_USER)
  local TARGET_USER="${SUDO_USER:-root}"
  local TARGET_HOME
  TARGET_HOME="$(eval echo "~$TARGET_USER")"
  [ -n "$TARGET_HOME" ] || die "Impossible de résoudre le HOME de $TARGET_USER"
  echo "Ajout de la clé SSH pour: $TARGET_USER ($TARGET_HOME)"
  # Création du dossier .ssh
  mkdir -p "$TARGET_HOME/.ssh"
  chown "$TARGET_USER:$TARGET_USER" "$TARGET_HOME/.ssh"
  chmod 700 "$TARGET_HOME/.ssh"
  # Fichier authorized_keys
  touch "$TARGET_HOME/.ssh/authorized_keys"
  chown "$TARGET_USER:$TARGET_USER" "$TARGET_HOME/.ssh/authorized_keys"
  chmod 600 "$TARGET_HOME/.ssh/authorized_keys"
  # Ajout clé si absente
  grep -qxF "$CLE_SSH_P" "$TARGET_HOME/.ssh/authorized_keys" || \
  echo "$CLE_SSH_P" >> "$TARGET_HOME/.ssh/authorized_keys"
  # Validation avant restart
  command -v sshd >/dev/null 2>&1 && sshd -t || { echo "ERREUR: sshd_config invalide. Restauration..."; [ -f "$BACKUP_FILE" ] && cp "$BACKUP_FILE" "$SSH_CONFIG"; exit 1; }
  echo "Redémarrage SSH..."
  if systemctl list-units --type=service | grep -q "sshd.service"; then
    systemctl restart sshd
  else
    systemctl restart ssh
  fi
}
show_summary() {
  echo ""
  echo "=== Terminé ==="
  echo "IP: $STATIC_IP"
  echo "Gateway: $GATEWAY"
  echo "DNS: ${DNS_LIST[*]}"
  [ "${#SEARCH_DOMAINS[@]}" -gt 0 ] && echo "Search domains: ${SEARCH_DOMAINS[*]}"
  echo "SSH Port: $SSH_PORT"
  echo "Root login: désactivé"
  echo "Password auth: désactivée (clé uniquement)"
  echo ""
  echo "ATTENTION: teste un nouvel accès SSH avant de fermer cette session !"
  echo "Ex: ssh -p $SSH_PORT <user>@${STATIC_IP%/*}"
}

# =========================
# MAIN
# =========================
echo "============================================================================"
echo "  Debian ONLY - Configuration Réseau + DNS + SSH Hardening"
echo "============================================================================"
echo ""
# Vérif Debian 
if [ -f /etc/os-release ]; then
  . /etc/os-release || true
  if [ "${ID:-}" != "debian" ] && [[ "${ID_LIKE:-}" != *"debian"* ]]; then
    echo "AVERTISSEMENT: script prévu pour Debian. Détecté: ${ID:-unknown}"
  fi
fi

configure_network_debian
configure_resolv_conf
rollback_resolv_conf_if_needed
configure_ssh_security
show_summary
