#!/bin/bash
set -euo pipefail

STATIC_IP="10.0.0.202/24"
GATEWAY="10.0.0.254"
DNS_LIST=("10.0.0.254" "1.1.1.1" "1.0.0.1")
SEARCH_DOMAINS=("test.auvergneinfo.lan")
SSH_PORT="22"

# Remplace par ta vraie clé publique complète
CLE_SSH_PUBLIC="ssh-ed25519 AAAAC... steph@POC-PC"

die() {
  echo "ERREUR: $*" >&2
  exit 1
}

check_sudo() {
  if [ "${EUID}" -ne 0 ]; then
    echo "Ce script nécessite des privilèges administrateur."
    echo "Relancement avec sudo..."
    exec sudo -E "$0" "$@"
  fi
}
check_sudo "$@"

validate_ssh_key() {
  echo "=== Validation clé SSH publique ==="
  local tmpkey
  tmpkey="$(mktemp)"
  echo "$CLE_SSH_PUBLIC" > "$tmpkey"

  if ! ssh-keygen -l -f "$tmpkey" >/dev/null 2>&1; then
    rm -f "$tmpkey"
    die "Clé SSH publique invalide. Remplace CLE_SSH_PUBLIC par une vraie clé publique complète."
  fi

  rm -f "$tmpkey"
  echo "Clé SSH valide."
}

detect_interface() {
  local iface
  iface="$(ip -o -4 route show to default 2>/dev/null | awk '{print $5}' | head -n1)"
  [ -n "$iface" ] || die "Impossible de détecter l'interface par défaut."
  echo "$iface"
}

prefix_to_netmask() {
  local p="$1"
  [ "$p" -ge 0 ] 2>/dev/null && [ "$p" -le 32 ] || die "Prefix invalide: $p"

  local full=$((p / 8))
  local rem=$((p % 8))
  local i mask=()

  for i in 0 1 2 3; do
    if [ "$i" -lt "$full" ]; then
      mask+=("255")
    elif [ "$i" -eq "$full" ]; then
      if [ "$rem" -eq 0 ]; then
        mask+=("0")
      else
        mask+=("$((256 - (1 << (8 - rem))))")
      fi
    else
      mask+=("0")
    fi
  done

  echo "${mask[0]}.${mask[1]}.${mask[2]}.${mask[3]}"
}

configure_network_debian() {
  echo "=== Configuration réseau Debian ifupdown ==="

  local iface ip_addr prefix netmask dns_debian backup
  iface="$(detect_interface)"
  echo "Interface détectée: $iface"

  ip_addr="${STATIC_IP%/*}"
  prefix="${STATIC_IP#*/}"
  netmask="$(prefix_to_netmask "$prefix")"
  dns_debian="$(printf '%s ' "${DNS_LIST[@]}")"

  [ -f /etc/network/interfaces ] || die "/etc/network/interfaces introuvable. ifupdown requis."

  backup="/etc/network/interfaces.backup.$(date +%F-%H%M%S)"
  cp /etc/network/interfaces "$backup"
  echo "Backup créé: $backup"

  cat > /etc/network/interfaces <<EOF
# ============================================================================
# /etc/network/interfaces - généré automatiquement le $(date)
# Backup: $backup
# ============================================================================

auto lo
iface lo inet loopback

allow-hotplug $iface
iface $iface inet static
  address $ip_addr
  netmask $netmask
  gateway $GATEWAY
  dns-nameservers $dns_debian
EOF

  echo "Redémarrage réseau..."
  if systemctl list-unit-files | grep -q '^networking\.service'; then
    systemctl restart networking.service || die "Échec restart networking.service"
  else
    ifdown "$iface" 2>/dev/null || true
    ifup "$iface" || die "Échec ifup $iface"
  fi

  echo "Réseau configuré: $ip_addr/$prefix via $GATEWAY"
}

configure_resolv_conf() {
  echo "=== Configuration DNS ==="

  local RESOLV="/etc/resolv.conf"
  local backup="/etc/resolv.conf.backup.$(date +%F-%H%M%S)"
  local tmp

  RESOLV_BACKUP=""

  if [ -e "$RESOLV" ]; then
    cp -a "$RESOLV" "$backup"
    RESOLV_BACKUP="$backup"
    echo "Backup créé: $backup"
  fi

  tmp="$(mktemp)"

  {
    echo "# Generated by Debian-only network script on $(date)"

    if [ "${#SEARCH_DOMAINS[@]}" -gt 0 ]; then
      echo "search ${SEARCH_DOMAINS[*]}"
    fi

    for dns in "${DNS_LIST[@]}"; do
      echo "nameserver $dns"
    done
  } > "$tmp"

  if command -v resolvconf >/dev/null 2>&1; then
    echo "resolvconf détecté."
    mkdir -p /etc/resolvconf/resolv.conf.d
    cp "$tmp" /etc/resolvconf/resolv.conf.d/head
    resolvconf -u || die "Échec resolvconf -u"
    rm -f "$tmp"
    return 0
  fi

  if systemctl is-active --quiet systemd-resolved 2>/dev/null && [ -L "$RESOLV" ]; then
    echo "systemd-resolved actif avec /etc/resolv.conf en symlink."

    local rbackup="/etc/systemd/resolved.conf.backup.$(date +%F-%H%M%S)"
    local domains=""

    [ -f /etc/systemd/resolved.conf ] && cp /etc/systemd/resolved.conf "$rbackup" && echo "Backup: $rbackup"

    if [ "${#SEARCH_DOMAINS[@]}" -gt 0 ]; then
      domains="${SEARCH_DOMAINS[*]}"
    fi

    cat > /etc/systemd/resolved.conf <<EOF
[Resolve]
DNS=${DNS_LIST[*]}
Domains=${domains}
EOF

    systemctl restart systemd-resolved || die "Échec restart systemd-resolved"
    rm -f "$tmp"
    return 0
  fi

  echo "Écriture directe de /etc/resolv.conf"
  cp "$tmp" "$RESOLV"
  chmod 644 "$RESOLV"
  rm -f "$tmp"
}

test_dns() {
  echo "=== Test DNS ==="
  sed -n '1,120p' /etc/resolv.conf || true

  local missing=0

  for dns in "${DNS_LIST[@]}"; do
    if awk -v dns="$dns" '$1=="nameserver" && $2==dns {found=1} END{exit !found}' /etc/resolv.conf; then
      echo "OK: $dns"
    else
      echo "KO: $dns absent"
      missing=1
    fi
  done

  if getent hosts google.com >/dev/null 2>&1; then
    echo "Résolution DNS: OK"
    return "$missing"
  else
    echo "Résolution DNS: ECHEC"
    return 1
  fi
}

rollback_resolv_conf_if_needed() {
  echo "=== Validation DNS ==="

  if test_dns; then
    echo "DNS validé."
    return 0
  fi

  echo "DNS invalide, rollback..."

  if [ -n "${RESOLV_BACKUP:-}" ] && [ -e "$RESOLV_BACKUP" ]; then
    cp -a "$RESOLV_BACKUP" /etc/resolv.conf
    chmod 644 /etc/resolv.conf || true
    echo "Rollback effectué depuis: $RESOLV_BACKUP"
  else
    die "Aucun backup resolv.conf disponible."
  fi

  test_dns || die "DNS toujours invalide après rollback."
}

configure_ssh_security() {
  echo "=== Sécurisation SSH ==="

  local SSH_CONFIG="/etc/ssh/sshd_config"
  local BACKUP_FILE="/etc/ssh/sshd_config.backup.$(date +%F-%H%M%S)"
  local SFTP_PATH
  local TARGET_USER TARGET_HOME TARGET_GROUP SSHD_BIN

  if [ -x /usr/libexec/openssh/sftp-server ]; then
    SFTP_PATH="/usr/libexec/openssh/sftp-server"
  elif [ -x /usr/lib/openssh/sftp-server ]; then
    SFTP_PATH="/usr/lib/openssh/sftp-server"
  else
    SFTP_PATH="internal-sftp"
  fi

  [ -f "$SSH_CONFIG" ] && cp "$SSH_CONFIG" "$BACKUP_FILE" && echo "Backup créé: $BACKUP_FILE"

  cat > "$SSH_CONFIG" <<EOF
# ============================================================================
# SSHD Configuration - Hardened Debian
# Généré automatiquement le $(date)
# ============================================================================

Port $SSH_PORT
Protocol 2

PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
PermitEmptyPasswords no

MaxAuthTries 3
LoginGraceTime 30

X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding no
PermitTunnel no

AuthorizedKeysFile .ssh/authorized_keys

SyslogFacility AUTH
LogLevel VERBOSE

UsePAM yes

Subsystem sftp $SFTP_PATH
EOF

  chmod 600 "$SSH_CONFIG"

  TARGET_USER="${SUDO_USER:-root}"
  TARGET_HOME="$(getent passwd "$TARGET_USER" | cut -d: -f6)"
  TARGET_GROUP="$(id -gn "$TARGET_USER")"

  [ -n "$TARGET_HOME" ] && [ -d "$TARGET_HOME" ] || die "HOME invalide pour $TARGET_USER"

  if [ "$TARGET_USER" != "root" ]; then
    id -nG "$TARGET_USER" | grep -qw sudo || die "$TARGET_USER n'est pas dans le groupe sudo"
  fi

  echo "Ajout de la clé SSH pour: $TARGET_USER ($TARGET_HOME)"

  mkdir -p "$TARGET_HOME/.ssh"
  chown "$TARGET_USER:$TARGET_GROUP" "$TARGET_HOME/.ssh"
  chmod 700 "$TARGET_HOME/.ssh"

  touch "$TARGET_HOME/.ssh/authorized_keys"
  chown "$TARGET_USER:$TARGET_GROUP" "$TARGET_HOME/.ssh/authorized_keys"
  chmod 600 "$TARGET_HOME/.ssh/authorized_keys"

  grep -qxF "$CLE_SSH_P" "$TARGET_HOME/.ssh/authorized_keys" || echo "$CLE_SSH_PUBLIC" >> "$TARGET_HOME/.ssh/authorized_keys"

  SSHD_BIN="$(command -v sshd || true)"
  [ -n "$SSHD_BIN" ] || SSHD_BIN="/usr/sbin/sshd"
  [ -x "$SSHD_BIN" ] || die "sshd introuvable"

  "$SSHD_BIN" -t || {
    echo "ERREUR: sshd_config invalide. Restauration..."
    [ -f "$BACKUP_FILE" ] && cp "$BACKUP_FILE" "$SSH_CONFIG"
    exit 1
  }

  echo "Redémarrage SSH..."
  if systemctl list-units --type=service | grep -q "sshd.service"; then
    systemctl restart sshd
  else
    systemctl restart ssh
  fi
}

show_summary() {
  echo ""
  echo "=== Terminé ==="
  echo "IP: $STATIC_IP"
  echo "Gateway: $GATEWAY"
  echo "DNS: ${DNS_LIST[*]}"
  [ "${#SEARCH_DOMAINS[@]}" -gt 0 ] && echo "Search domains: ${SEARCH_DOMAINS[*]}"
  echo "SSH Port: $SSH_PORT"
  echo "Root login: désactivé"
  echo "Password auth: désactivée"
  echo ""
  echo "Teste un nouvel accès SSH avant de considérer la machine finalisée."
  echo "Exemple:"
  echo "ssh -p $SSH_PORT ${SUDO_USER:-user}@${STATIC_IP%/*}"
}

echo "============================================================================"
echo " Debian ONLY - Configuration Réseau + DNS + SSH Hardening"
echo "============================================================================"

if [ -f /etc/os-release ]; then
  . /etc/os-release || true
  if [ "${ID:-}" != "debian" ] && [[ "${ID_LIKE:-}" != *"debian"* ]]; then
    echo "AVERTISSEMENT: script prévu pour Debian. Détecté: ${ID:-unknown}"
  fi
fi

validate_ssh_key
configure_network_debian
configure_resolv_conf
rollback_resolv_conf_if_needed
configure_ssh_security
show_summary
